title: Such improve, so amaze - Wow! 
description: > # this means to ignore newlines until "baseurl:"
  Android Engineer and Architect with over 6 years of track record in building mobile products to enter new markets and scale to various countries across the globe. Strong passion for creating user-centric products by considering limitations and capabilities of software implementation.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Johannes Neutze # add your name
author-img: johannes-neutze.jpg # add your photo
about-author: Android Engineer and Architect with over 6 years of track record in building mobile products to enter new markets and scale to various countries across the globe. Strong passion for creating user-centric products by considering limitations and capabilities of software implementation. # add description
social-twitter: johannes-neutze.jpg # add your Twitter handle
social-facebook: johannes.neutze # add your Facebook handle
social-github: neutze # add your Github handle
social-linkedin: johannes-neutze # add your Linkedin handle
social-email: johannes@neutze.de # add your Email address

# Disqus
discus-identifier: neutze # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
